#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to install
# HAProxy and configures it to load balance to 2 servers using the
# roundrobin algorithm.
sudo apt update
sudo apt-get install haproxy -y
echo -e "\nfrontend http
\tbind *:80
\tdefault_backend web-backend


backend web-backend
\tbalance roundrobin
\tserver web1 100.25.144.140:80 check
\tserver web2 18.210.16.190:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo service haproxy restart
